/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdopcionRouteImport } from './routes/adopcion'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BienvenidaRouteImport } from './routes/bienvenida'
import { Route as ExplorarRouteImport } from './routes/explorar'
import { Route as MapaRouteImport } from './routes/mapa'
import { Route as MisPublicacionesRouteImport } from './routes/mis-publicaciones'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as PublicarRouteImport } from './routes/publicar'
import { Route as ReencuentrosRouteImport } from './routes/reencuentros'
import { Route as MascotaIdRouteImport } from './routes/mascota.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdopcionRoute = AdopcionRouteImport.update({
  id: '/adopcion',
  path: '/adopcion',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BienvenidaRoute = BienvenidaRouteImport.update({
  id: '/bienvenida',
  path: '/bienvenida',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorarRoute = ExplorarRouteImport.update({
  id: '/explorar',
  path: '/explorar',
  getParentRoute: () => rootRouteImport,
} as any)
const MapaRoute = MapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => rootRouteImport,
} as any)
const MisPublicacionesRoute = MisPublicacionesRouteImport.update({
  id: '/mis-publicaciones',
  path: '/mis-publicaciones',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicarRoute = PublicarRouteImport.update({
  id: '/publicar',
  path: '/publicar',
  getParentRoute: () => rootRouteImport,
} as any)
const ReencuentrosRoute = ReencuentrosRouteImport.update({
  id: '/reencuentros',
  path: '/reencuentros',
  getParentRoute: () => rootRouteImport,
} as any)
const MascotaIdRoute = MascotaIdRouteImport.update({
  id: '/mascota/$id',
  path: '/mascota/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/adopcion': typeof AdopcionRoute
  '/auth': typeof AuthRoute
  '/bienvenida': typeof BienvenidaRoute
  '/explorar': typeof ExplorarRoute
  '/mapa': typeof MapaRoute
  '/mis-publicaciones': typeof MisPublicacionesRoute
  '/perfil': typeof PerfilRoute
  '/publicar': typeof PublicarRoute
  '/reencuentros': typeof ReencuentrosRoute
  '/mascota/$id': typeof MascotaIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/adopcion': typeof AdopcionRoute
  '/auth': typeof AuthRoute
  '/bienvenida': typeof BienvenidaRoute
  '/explorar': typeof ExplorarRoute
  '/mapa': typeof MapaRoute
  '/mis-publicaciones': typeof MisPublicacionesRoute
  '/perfil': typeof PerfilRoute
  '/publicar': typeof PublicarRoute
  '/reencuentros': typeof ReencuentrosRoute
  '/mascota/$id': typeof MascotaIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/adopcion': typeof AdopcionRoute
  '/auth': typeof AuthRoute
  '/bienvenida': typeof BienvenidaRoute
  '/explorar': typeof ExplorarRoute
  '/mapa': typeof MapaRoute
  '/mis-publicaciones': typeof MisPublicacionesRoute
  '/perfil': typeof PerfilRoute
  '/publicar': typeof PublicarRoute
  '/reencuentros': typeof ReencuentrosRoute
  '/mascota/$id': typeof MascotaIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/adopcion'
    | '/auth'
    | '/bienvenida'
    | '/explorar'
    | '/mapa'
    | '/mis-publicaciones'
    | '/perfil'
    | '/publicar'
    | '/reencuentros'
    | '/mascota/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/adopcion'
    | '/auth'
    | '/bienvenida'
    | '/explorar'
    | '/mapa'
    | '/mis-publicaciones'
    | '/perfil'
    | '/publicar'
    | '/reencuentros'
    | '/mascota/$id'
  id:
    | '__root__'
    | '/'
    | '/adopcion'
    | '/auth'
    | '/bienvenida'
    | '/explorar'
    | '/mapa'
    | '/mis-publicaciones'
    | '/perfil'
    | '/publicar'
    | '/reencuentros'
    | '/mascota/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdopcionRoute: typeof AdopcionRoute
  AuthRoute: typeof AuthRoute
  BienvenidaRoute: typeof BienvenidaRoute
  ExplorarRoute: typeof ExplorarRoute
  MapaRoute: typeof MapaRoute
  MisPublicacionesRoute: typeof MisPublicacionesRoute
  PerfilRoute: typeof PerfilRoute
  PublicarRoute: typeof PublicarRoute
  ReencuentrosRoute: typeof ReencuentrosRoute
  MascotaIdRoute: typeof MascotaIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adopcion': {
      id: '/adopcion'
      path: '/adopcion'
      fullPath: '/adopcion'
      preLoaderRoute: typeof AdopcionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bienvenida': {
      id: '/bienvenida'
      path: '/bienvenida'
      fullPath: '/bienvenida'
      preLoaderRoute: typeof BienvenidaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explorar': {
      id: '/explorar'
      path: '/explorar'
      fullPath: '/explorar'
      preLoaderRoute: typeof ExplorarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapa': {
      id: '/mapa'
      path: '/mapa'
      fullPath: '/mapa'
      preLoaderRoute: typeof MapaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mis-publicaciones': {
      id: '/mis-publicaciones'
      path: '/mis-publicaciones'
      fullPath: '/mis-publicaciones'
      preLoaderRoute: typeof MisPublicacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publicar': {
      id: '/publicar'
      path: '/publicar'
      fullPath: '/publicar'
      preLoaderRoute: typeof PublicarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reencuentros': {
      id: '/reencuentros'
      path: '/reencuentros'
      fullPath: '/reencuentros'
      preLoaderRoute: typeof ReencuentrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mascota/$id': {
      id: '/mascota/$id'
      path: '/mascota/$id'
      fullPath: '/mascota/$id'
      preLoaderRoute: typeof MascotaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdopcionRoute: AdopcionRoute,
  AuthRoute: AuthRoute,
  BienvenidaRoute: BienvenidaRoute,
  ExplorarRoute: ExplorarRoute,
  MapaRoute: MapaRoute,
  MisPublicacionesRoute: MisPublicacionesRoute,
  PerfilRoute: PerfilRoute,
  PublicarRoute: PublicarRoute,
  ReencuentrosRoute: ReencuentrosRoute,
  MascotaIdRoute: MascotaIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
